export const vendingActionTypes = {
  GET_PRODUCTS: "GET_PRODUCTS",
  CLEAR_PRODUCTS: "CLEAR_PRODUCTS",
  REMOVE_ITEM_FROM_STOCK: "REMOVE_ITEM_FROM_STOCK",
  ADD_FUNDS: "ADD_FUNDS",
  REPLEN_ITEM: "REPLEN_ITEM",
};
